---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/mnt/3scale/jenkins"
    server: 10.19.137.31
claimRef:
  namespace: jenkins-for-broker
  name: jenkins

