//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 07:46:09 PM PST 
//


package com.redhat.syseng.openshift.service.broker.model.amp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.redhat.syseng.openshift.service.broker.model.amp package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MappingRules_QNAME = new QName("", "mapping_rules");
    private final static QName _Proxy_QNAME = new QName("", "proxy");
    private final static QName _Plans_QNAME = new QName("", "plans");
    private final static QName _Services_QNAME = new QName("", "services");
    private final static QName _Users_QNAME = new QName("", "users");
    private final static QName _Applications_QNAME = new QName("", "applications");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.redhat.syseng.openshift.service.broker.model.amp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MappingRules }
     * 
     */
    public MappingRules createMappingRules() {
        return new MappingRules();
    }

    /**
     * Create an instance of {@link Proxy }
     * 
     */
    public Proxy createProxy() {
        return new Proxy();
    }

    /**
     * Create an instance of {@link Plans }
     * 
     */
    public Plans createPlans() {
        return new Plans();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link Users }
     * 
     */
    public Users createUsers() {
        return new Users();
    }

    /**
     * Create an instance of {@link Applications }
     * 
     */
    public Applications createApplications() {
        return new Applications();
    }

    /**
     * Create an instance of {@link MappingRule }
     * 
     */
    public MappingRule createMappingRule() {
        return new MappingRule();
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link Metric }
     * 
     */
    public Metric createMetric() {
        return new Metric();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Metrics }
     * 
     */
    public Metrics createMetrics() {
        return new Metrics();
    }

    /**
     * Create an instance of {@link Plan }
     * 
     */
    public Plan createPlan() {
        return new Plan();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MappingRules }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mapping_rules")
    public JAXBElement<MappingRules> createMappingRules(MappingRules value) {
        return new JAXBElement<MappingRules>(_MappingRules_QNAME, MappingRules.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Proxy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "proxy")
    public JAXBElement<Proxy> createProxy(Proxy value) {
        return new JAXBElement<Proxy>(_Proxy_QNAME, Proxy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Plans }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plans")
    public JAXBElement<Plans> createPlans(Plans value) {
        return new JAXBElement<Plans>(_Plans_QNAME, Plans.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Services }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "services")
    public JAXBElement<Services> createServices(Services value) {
        return new JAXBElement<Services>(_Services_QNAME, Services.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Users }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "users")
    public JAXBElement<Users> createUsers(Users value) {
        return new JAXBElement<Users>(_Users_QNAME, Users.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Applications }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "applications")
    public JAXBElement<Applications> createApplications(Applications value) {
        return new JAXBElement<Applications>(_Applications_QNAME, Applications.class, null, value);
    }

}
