//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 07:46:09 PM PST 
//


package com.redhat.syseng.openshift.service.broker.model.amp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for proxy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="proxy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="service_id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="endpoint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="api_backend" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="credentials_location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="auth_app_key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="auth_app_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="auth_user_key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="error_auth_failed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="error_auth_missing" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="error_status_auth_failed" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="error_headers_auth_failed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="error_status_auth_missing" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="error_headers_auth_missing" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="error_no_match" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="error_status_no_match" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="error_headers_no_match" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="secret_token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sandbox_endpoint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="api_test_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="created_at" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="updated_at" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "proxy", propOrder = {
    "serviceId",
    "endpoint",
    "apiBackend",
    "credentialsLocation",
    "authAppKey",
    "authAppId",
    "authUserKey",
    "errorAuthFailed",
    "errorAuthMissing",
    "errorStatusAuthFailed",
    "errorHeadersAuthFailed",
    "errorStatusAuthMissing",
    "errorHeadersAuthMissing",
    "errorNoMatch",
    "errorStatusNoMatch",
    "errorHeadersNoMatch",
    "secretToken",
    "sandboxEndpoint",
    "apiTestPath",
    "createdAt",
    "updatedAt"
})
public class Proxy {

    @XmlElement(name = "service_id")
    protected byte serviceId;
    @XmlElement(required = true)
    protected String endpoint;
    @XmlElement(name = "api_backend", required = true)
    protected String apiBackend;
    @XmlElement(name = "credentials_location", required = true)
    protected String credentialsLocation;
    @XmlElement(name = "auth_app_key", required = true)
    protected String authAppKey;
    @XmlElement(name = "auth_app_id", required = true)
    protected String authAppId;
    @XmlElement(name = "auth_user_key", required = true)
    protected String authUserKey;
    @XmlElement(name = "error_auth_failed", required = true)
    protected String errorAuthFailed;
    @XmlElement(name = "error_auth_missing", required = true)
    protected String errorAuthMissing;
    @XmlElement(name = "error_status_auth_failed")
    protected short errorStatusAuthFailed;
    @XmlElement(name = "error_headers_auth_failed", required = true)
    protected String errorHeadersAuthFailed;
    @XmlElement(name = "error_status_auth_missing")
    protected short errorStatusAuthMissing;
    @XmlElement(name = "error_headers_auth_missing", required = true)
    protected String errorHeadersAuthMissing;
    @XmlElement(name = "error_no_match", required = true)
    protected String errorNoMatch;
    @XmlElement(name = "error_status_no_match")
    protected short errorStatusNoMatch;
    @XmlElement(name = "error_headers_no_match", required = true)
    protected String errorHeadersNoMatch;
    @XmlElement(name = "secret_token", required = true)
    protected String secretToken;
    @XmlElement(name = "sandbox_endpoint", required = true)
    protected String sandboxEndpoint;
    @XmlElement(name = "api_test_path", required = true)
    protected String apiTestPath;
    @XmlElement(name = "created_at", required = true)
    protected String createdAt;
    @XmlElement(name = "updated_at", required = true)
    protected String updatedAt;

    /**
     * Gets the value of the serviceId property.
     * 
     */
    public byte getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     */
    public void setServiceId(byte value) {
        this.serviceId = value;
    }

    /**
     * Gets the value of the endpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndpoint() {
        return endpoint;
    }

    /**
     * Sets the value of the endpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndpoint(String value) {
        this.endpoint = value;
    }

    /**
     * Gets the value of the apiBackend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApiBackend() {
        return apiBackend;
    }

    /**
     * Sets the value of the apiBackend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApiBackend(String value) {
        this.apiBackend = value;
    }

    /**
     * Gets the value of the credentialsLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCredentialsLocation() {
        return credentialsLocation;
    }

    /**
     * Sets the value of the credentialsLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCredentialsLocation(String value) {
        this.credentialsLocation = value;
    }

    /**
     * Gets the value of the authAppKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthAppKey() {
        return authAppKey;
    }

    /**
     * Sets the value of the authAppKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthAppKey(String value) {
        this.authAppKey = value;
    }

    /**
     * Gets the value of the authAppId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthAppId() {
        return authAppId;
    }

    /**
     * Sets the value of the authAppId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthAppId(String value) {
        this.authAppId = value;
    }

    /**
     * Gets the value of the authUserKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthUserKey() {
        return authUserKey;
    }

    /**
     * Sets the value of the authUserKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthUserKey(String value) {
        this.authUserKey = value;
    }

    /**
     * Gets the value of the errorAuthFailed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorAuthFailed() {
        return errorAuthFailed;
    }

    /**
     * Sets the value of the errorAuthFailed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorAuthFailed(String value) {
        this.errorAuthFailed = value;
    }

    /**
     * Gets the value of the errorAuthMissing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorAuthMissing() {
        return errorAuthMissing;
    }

    /**
     * Sets the value of the errorAuthMissing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorAuthMissing(String value) {
        this.errorAuthMissing = value;
    }

    /**
     * Gets the value of the errorStatusAuthFailed property.
     * 
     */
    public short getErrorStatusAuthFailed() {
        return errorStatusAuthFailed;
    }

    /**
     * Sets the value of the errorStatusAuthFailed property.
     * 
     */
    public void setErrorStatusAuthFailed(short value) {
        this.errorStatusAuthFailed = value;
    }

    /**
     * Gets the value of the errorHeadersAuthFailed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorHeadersAuthFailed() {
        return errorHeadersAuthFailed;
    }

    /**
     * Sets the value of the errorHeadersAuthFailed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorHeadersAuthFailed(String value) {
        this.errorHeadersAuthFailed = value;
    }

    /**
     * Gets the value of the errorStatusAuthMissing property.
     * 
     */
    public short getErrorStatusAuthMissing() {
        return errorStatusAuthMissing;
    }

    /**
     * Sets the value of the errorStatusAuthMissing property.
     * 
     */
    public void setErrorStatusAuthMissing(short value) {
        this.errorStatusAuthMissing = value;
    }

    /**
     * Gets the value of the errorHeadersAuthMissing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorHeadersAuthMissing() {
        return errorHeadersAuthMissing;
    }

    /**
     * Sets the value of the errorHeadersAuthMissing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorHeadersAuthMissing(String value) {
        this.errorHeadersAuthMissing = value;
    }

    /**
     * Gets the value of the errorNoMatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorNoMatch() {
        return errorNoMatch;
    }

    /**
     * Sets the value of the errorNoMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorNoMatch(String value) {
        this.errorNoMatch = value;
    }

    /**
     * Gets the value of the errorStatusNoMatch property.
     * 
     */
    public short getErrorStatusNoMatch() {
        return errorStatusNoMatch;
    }

    /**
     * Sets the value of the errorStatusNoMatch property.
     * 
     */
    public void setErrorStatusNoMatch(short value) {
        this.errorStatusNoMatch = value;
    }

    /**
     * Gets the value of the errorHeadersNoMatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorHeadersNoMatch() {
        return errorHeadersNoMatch;
    }

    /**
     * Sets the value of the errorHeadersNoMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorHeadersNoMatch(String value) {
        this.errorHeadersNoMatch = value;
    }

    /**
     * Gets the value of the secretToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecretToken() {
        return secretToken;
    }

    /**
     * Sets the value of the secretToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecretToken(String value) {
        this.secretToken = value;
    }

    /**
     * Gets the value of the sandboxEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSandboxEndpoint() {
        return sandboxEndpoint;
    }

    /**
     * Sets the value of the sandboxEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSandboxEndpoint(String value) {
        this.sandboxEndpoint = value;
    }

    /**
     * Gets the value of the apiTestPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApiTestPath() {
        return apiTestPath;
    }

    /**
     * Sets the value of the apiTestPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApiTestPath(String value) {
        this.apiTestPath = value;
    }

    /**
     * Gets the value of the createdAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the value of the createdAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedAt(String value) {
        this.createdAt = value;
    }

    /**
     * Gets the value of the updatedAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the value of the updatedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedAt(String value) {
        this.updatedAt = value;
    }

}
