//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.06 at 11:27:23 AM EST 
//


package com.redhat.syseng.openshift.service.broker.model.amp;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for service complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="account_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="system_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="backend_version" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="end_user_registration_required" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="metrics">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="metric">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="system_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="friendly_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="service_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "accountId",
    "name",
    "state",
    "systemName",
    "backendVersion",
    "endUserRegistrationRequired",
    "metrics"
})
@XmlRootElement(name = "service")
public class Service {

    protected int id;
    @XmlElement(name = "account_id")
    protected int accountId;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String state;
    @XmlElement(name = "system_name", required = true)
    protected String systemName;
    @XmlElement(name = "backend_version")
    protected int backendVersion;
    @XmlElement(name = "end_user_registration_required", required = true)
    protected String endUserRegistrationRequired;
    @XmlElement(required = true)
    protected Service.Metrics metrics;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the accountId property.
     * 
     */
    public int getAccountId() {
        return accountId;
    }

    /**
     * Sets the value of the accountId property.
     * 
     */
    public void setAccountId(int value) {
        this.accountId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the systemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * Sets the value of the systemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemName(String value) {
        this.systemName = value;
    }

    /**
     * Gets the value of the backendVersion property.
     * 
     */
    public int getBackendVersion() {
        return backendVersion;
    }

    /**
     * Sets the value of the backendVersion property.
     * 
     */
    public void setBackendVersion(int value) {
        this.backendVersion = value;
    }

    /**
     * Gets the value of the endUserRegistrationRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndUserRegistrationRequired() {
        return endUserRegistrationRequired;
    }

    /**
     * Sets the value of the endUserRegistrationRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndUserRegistrationRequired(String value) {
        this.endUserRegistrationRequired = value;
    }

    /**
     * Gets the value of the metrics property.
     * 
     * @return
     *     possible object is
     *     {@link Service.Metrics }
     *     
     */
    public Service.Metrics getMetrics() {
        return metrics;
    }

    /**
     * Sets the value of the metrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Service.Metrics }
     *     
     */
    public void setMetrics(Service.Metrics value) {
        this.metrics = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="metric">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="system_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="friendly_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="service_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "metric"
    })
    public static class Metrics {

        @XmlElement(required = true)
        protected Service.Metrics.Metric metric;

        /**
         * Gets the value of the metric property.
         * 
         * @return
         *     possible object is
         *     {@link Service.Metrics.Metric }
         *     
         */
        public Service.Metrics.Metric getMetric() {
            return metric;
        }

        /**
         * Sets the value of the metric property.
         * 
         * @param value
         *     allowed object is
         *     {@link Service.Metrics.Metric }
         *     
         */
        public void setMetric(Service.Metrics.Metric value) {
            this.metric = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="system_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="friendly_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="service_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "name",
            "systemName",
            "friendlyName",
            "serviceId",
            "description",
            "unit"
        })
        public static class Metric {

            protected int id;
            @XmlElement(required = true)
            protected String name;
            @XmlElement(name = "system_name", required = true)
            protected String systemName;
            @XmlElement(name = "friendly_name", required = true)
            protected String friendlyName;
            @XmlElement(name = "service_id")
            protected int serviceId;
            @XmlElement(required = true)
            protected String description;
            @XmlElement(required = true)
            protected String unit;

            /**
             * Gets the value of the id property.
             * 
             */
            public int getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(int value) {
                this.id = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the systemName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSystemName() {
                return systemName;
            }

            /**
             * Sets the value of the systemName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSystemName(String value) {
                this.systemName = value;
            }

            /**
             * Gets the value of the friendlyName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFriendlyName() {
                return friendlyName;
            }

            /**
             * Sets the value of the friendlyName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFriendlyName(String value) {
                this.friendlyName = value;
            }

            /**
             * Gets the value of the serviceId property.
             * 
             */
            public int getServiceId() {
                return serviceId;
            }

            /**
             * Sets the value of the serviceId property.
             * 
             */
            public void setServiceId(int value) {
                this.serviceId = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the unit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnit() {
                return unit;
            }

            /**
             * Sets the value of the unit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnit(String value) {
                this.unit = value;
            }

        }

    }

}